// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"$MUSH_MenuOptionScreenResolution_P1","status":true,"description":"[v.1.03] Adds the screen resolution option.","parameters":{"Resolution Command Name":"Screen Resolution","Resolution Options":"[[1280, 720],]","Scale Graphics":"false","Reposition Sprites":"true"}},
{"name":"ExitCommand","status":true,"description":"","parameters":{}},
{"name":"Dash","status":true,"description":"Plugin used to set basic parameters.","parameters":{"alwaysDash":"on"}},
{"name":"ShowConsole","status":true,"description":"Shows the developer console on boot.","parameters":{"Game Window X-Offset":"150","Game Window Y-Offset":"0","Autofocus":"true"}},
{"name":"test","status":true,"description":"","parameters":{}},
{"name":"services","status":true,"description":"","parameters":{}},
{"name":"RS_InputDialog","status":true,"description":"This plugin allows you to display Text Edit Box on the screen. <RS_InputDialog>","parameters":{"textBox Width":"488","textBox Height":"36","variable ID":"3","debug":"false","Text Hint":"Please enter the value...","direction":"ltr","Max Length":"255","Style":"","CSS":"\"\"","Button Name":"","Ok":"OK","Cancel":"Cancel","Position":"center"}}
];
